more than 1000 job array

diff --git a/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py b/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
--- a/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
+++ b/Alignment/HIPAlignmentAlgorithm/scripts/submitJobs_py
@@ -30,7 +30,11 @@ while (`bjobs -d -w |& grep $name/requeue$i` != "") # check if job name exists
   set name = $name/ # make job name unique to avoid name clash
 end
 
-echo Starting iteration = $i, final iteration = $iter, number of jobs = $jobs
+#echo Starting iteration = $i, final iteration = $iter, number of jobs = $jobs
+@ MAX_JOB_ARRAY_SIZE = `bparams -a | grep MAX_JOB_ARRAY_SIZE | sed "s/.* = //"`
+@ jobarrays = ( $jobs - 1 ) / $MAX_JOB_ARRAY_SIZE + 1
+
+echo Starting iteration = $i, final iteration = $iter, number of jobs = $jobs in $jobarrays arrays
 
 @ COLLECT_ERROR = 0
 while ($i <= $iter)
@@ -38,17 +42,40 @@ while ($i <= $iter)
   echo Running iteration $i
 
   if ($jobs > 0) then
-    @ j = 0 # job index
+#    @ j = 0 # job index
     echo "submit parallel jobs..."
-	bsub -q $queue -C 0 -J $name/align$i\[1-$jobs\] \
+#	bsub -q $queue -C 0 -J $name/align$i\[1-$jobs\] \
+    @ minjob = 1
+    foreach j (`seq 1 $jobarrays`)
+        @ maxjob = $minjob + $MAX_JOB_ARRAY_SIZE - 1
+        if ( $maxjob > $jobs ) then
+            @ maxjob = $jobs
+        endif
+	bsub -q $queue -C 0 -J $name/align"$i"_$j\[$minjob-$maxjob\] \
          -oo $odir/job%I/align$i.out $odir/job\$LSB_JOBINDEX/runScript.csh $workdir
-
+        @ minjob = $minjob + $MAX_JOB_ARRAY_SIZE
+    end
     sleep 15
-    set id = `bjobs -J $name/align$i | tail -n1 | awk '{print $1}'`
-    echo "ID=$id"
-		set idold = $id
+  #  set id = `bjobs -J $name/align$i | tail -n1 | awk '{print $1}'`
+  #  echo "ID=$id"
+	#	set idold = $id
+    foreach j (`seq 1 $jobarrays`)
+        set id = `bjobs -J $name/align"$i"_$j | tail -n1 | awk '{print $1}'`
+        echo "ID=$id"
+        if ( ! $?collectwaitcondition ) then
+            set collectwaitcondition = "done($id)"
+            set requeuewaitcondition = "numexit($id, > 0)"
+            set requeuejob = "brequeue -e $id"
+        else
+            set collectwaitcondition = "$collectwaitcondition && done($id)"
+            set requeuewaitcondition = "$requeuewaitcondition || numexit($id, > 0)"
+            set requeuejob = "$requeuejob || brequeue -e $id"    #this is a bit ugly, it will only requeue one array at a time
+                                                                 #it's needed to maintain the exit status of 0
+        endif
+    end
     echo "submit collect..."
-    bsub -q $queue -C 0 -J $name/collect$i\[1-$k\] -w "done($id)" \
+    #bsub -q $queue -C 0 -J $name/collect$i\[1-$k\] -w "done($id)" \
+    bsub -q $queue -C 0 -J $name/collect$i\[1-$k\] -w "$collectwaitcondition" \
     	   -oo $odir/main/collect$i"_"%I.out $odir/main/runScript_\$LSB_JOBINDEX.csh $workdir
 #    foreach line ( "`cat $odir/$iovfile`" )
 #  		echo $line
@@ -73,8 +100,10 @@ while ($i <= $iter)
 
     while (`bjobs -d -J $name/requeue$i |& grep EXIT` == "")
     echo "Submitting requeue"
-      bsub -q cmsinter -C 0 -J $name/requeue$i -w "numexit($idold, > 0)" \
-           -I brequeue -e $idold
+#      bsub -q cmsinter -C 0 -J $name/requeue$i -w "numexit($idold, > 0)" \
+#           -I brequeue -e $idold
+      bsub -q cmsinter -C 0 -J $name/requeue$i -w "$requeuewaitcondition" \
+           -I "$requeuejob"
       sleep 60
     end
 
