fixed ROOTSYS to be always external/root to avoid various issues with setting proper ROOTSYS. If default ROOT is not good, it can be replaced with a symbolic link

diff --git a/Fireworks/Core/scripts/Makefile b/Fireworks/Core/scripts/Makefile
--- a/Fireworks/Core/scripts/Makefile
+++ b/Fireworks/Core/scripts/Makefile
@@ -6,24 +6,26 @@ ifndef VERBOSE
   QUIET := @
 endif
 
+ROOTSYS = external/root
+
 all: display install
 
-core:   env Makefile.core
+core:   Makefile.core
 	$(QUIET) $(MAKE) -f Makefile.core
 	
-display: env Makefile.project
+display: Makefile.project
 	$(QUIET) $(MAKE) -f Makefile.project
 
-install: env Makefile.core
+install: Makefile.core
 	$(QUIET) $(MAKE) -f Makefile.core install;\
 	echo Done
 
 # check if proper environment is setup
-env: 
-	$(QUIET) if [ -z "$(ROOTSYS)" ]; then \
-	   echo "ROOTSYS not set. Abort."; \
-	   exit 1; \
-	fi;
+#env: 
+#	$(QUIET) if [ -z "$(ROOTSYS)" ]; then \
+#	   echo "ROOTSYS not set. Abort."; \
+#	   exit 1; \
+#	fi;
 
 clean: cleancore cleandisplay
 
