returning cmsTriton script to more up-to-date version before editing

diff --git a/HeterogeneousCore/SonicTriton/scripts/cmsTriton b/HeterogeneousCore/SonicTriton/scripts/cmsTriton
--- a/HeterogeneousCore/SonicTriton/scripts/cmsTriton
+++ b/HeterogeneousCore/SonicTriton/scripts/cmsTriton
@@ -20,7 +20,7 @@ PARENTPID=""
 BASEPORT=8000
 AUTOPORT=""
 NPORTS=3
-IMAGE=fastml/triton-torchgeo:21.06-py3-geometric
+IMAGE=fastml/triton-torchgeo:22.07-py3-geometric
 SANDBOX=""
 COMPAT_USR=""
 
@@ -40,7 +40,7 @@ usage() {
 	$ECHO "-c          \t don't cleanup temporary dir (for debugging)"
 	$ECHO "-C [dir]    \t directory containing Nvidia compatibility drivers (checks CMSSW_BASE by default if available)"
 	$ECHO "-D          \t dry run: print container commands rather than executing them"
-	$ECHO "-d          \t use Docker instead of Singularity"
+	$ECHO "-d          \t use Docker instead of Apptainer"
 	$ECHO "-f          \t force reuse of (possibly) existing container instance"
 	$ECHO "-g          \t use GPU instead of CPU"
 	$ECHO "-i [name]   \t server image name (default: ${IMAGE})"
@@ -51,7 +51,7 @@ usage() {
 	$ECHO "-P [port]   \t base port number for services (-1: automatically find an unused port range) (default: ${BASEPORT})"
 	$ECHO "-p [pid]    \t automatically shut down server when process w/ specified PID ends (-1: use parent process PID)"
 	$ECHO "-r [num]    \t number of retries when starting container (default: ${RETRIES})"
-	$ECHO "-s [dir]    \t Singularity sandbox directory (default: $(get_sandbox))"
+	$ECHO "-s [dir]    \t Apptainer sandbox directory (default: $(get_sandbox))"
 	$ECHO "-t [dir]    \t non-default hidden temporary dir"
 	$ECHO "-v          \t (verbose) start: activate server debugging info; stop: keep server logs"
 	$ECHO "-w [time]   \t maximum time to wait for server to start (default: ${WTIME} seconds)"
@@ -70,7 +70,7 @@ if [ -e /run/shm ]; then
 	SHM=/run/shm
 fi
 
-while getopts "cC:Ddfgi:M:m:n:P:p:r:s:t:I:vw:h" opt; do
+while getopts "cC:Ddfgi:I:M:m:n:P:p:r:s:t:vw:h" opt; do
 	case "$opt" in
 		c) CLEANUP=""
 		;;
@@ -85,6 +85,8 @@ while getopts "cC:Ddfgi:M:m:n:P:p:r:s:t:I:vw:h" opt; do
 		g) GPU=true
 		;;
 		i) IMAGE="$OPTARG"
+		;;
+		I) INSTANCES="$OPTARG"
 		;;
 		M) REPOS+=("$OPTARG")
 		;;
@@ -101,8 +103,6 @@ while getopts "cC:Ddfgi:M:m:n:P:p:r:s:t:I:vw:h" opt; do
 		s) SANDBOX="$OPTARG"
 		;;
 		t) TMPDIR="$OPTARG"
-		;;
-		I) INSTANCES="$OPTARG"
 		;;
 		v) VERBOSE="$VERBOSE_ARGS"
 		;;
@@ -131,9 +131,27 @@ else
 	TMPDIR=$(readlink -f $TMPDIR)
 fi
 
+# find executables
+if [ -n "$USEDOCKER" ]; then
+	if [ -z "$DOCKER" ]; then
+		DOCKER="sudo docker"
+	fi
+else
+	if [ -z "$APPTAINER" ]; then
+		if type apptainer >& /dev/null; then
+			APPTAINER=apptainer
+		elif type singularity >& /dev/null; then
+			APPTAINER=singularity
+		else
+			echo "Missing apptainer and singularity"
+			exit 1
+		fi
+	fi
+fi
+
+
 SANDBOX=$(get_sandbox)
 SANDBOX=$(readlink -f ${SANDBOX})
-DOCKER="sudo docker"
 LOG="log_${SERVER}.log"
 STOPLOG="log_stop_${SERVER}.log"
 LIB=lib
@@ -209,7 +227,7 @@ start_docker(){
 		${IMAGE} tritonserver $PORTARGS $REPOARGS $VERBOSE
 }
 
-start_singularity(){
+start_apptainer(){
 	# triton server image may need to modify contents of opt/tritonserver/lib/
 	# but cvmfs is read-only
 	# -> make a writable local directory with the same contents
@@ -246,7 +264,7 @@ start_singularity(){
 
 	# start instance
 	# need to bind /cvmfs for above symlinks to work inside container
-	$DRYRUN singularity instance start \
+	$DRYRUN $APPTAINER instance start \
 		-B ${SHM}:/run/shm -B ${LIB}:/opt/tritonserver/lib -B ${SANDBOX} $MOUNTARGS $EXTRA \
 		${SANDBOX} ${SERVER}
 
@@ -262,7 +280,7 @@ start_singularity(){
 	else
 		REDIR=/dev/stdout
 	fi
-	$DRYRUN singularity run instance://${SERVER} \
+	$DRYRUN $APPTAINER run instance://${SERVER} \
 		tritonserver $PORTARGS $REPOARGS $VERBOSE >& ${REDIR} &
 	[ -z "$DRYRUN" ] || wait
 }
@@ -277,8 +295,8 @@ stop_docker(){
 	$DRYRUN $DOCKER rm ${SERVER}
 }
 
-stop_singularity(){
-	$DRYRUN singularity instance stop ${SERVER}
+stop_apptainer(){
+	$DRYRUN $APPTAINER instance stop ${SERVER}
 }
 
 test_docker(){
@@ -286,7 +304,7 @@ test_docker(){
 	${DOCKER} logs ${SERVER} |& grep "$1"
 }
 
-test_singularity(){
+test_apptainer(){
 	grep "$1" $LOG
 }
 
@@ -323,13 +341,13 @@ wait_server(){
 edit_model(){
 	MODELNAME=$1
 	NUMINSTANCES=$2
-
+	
 	cp -r $MODELNAME $TMPDIR/$LOCALMODELREPO/
 	IFS='/' read -ra ADDR <<< "$MODELNAME"
 	CONFIG=$TMPDIR/$LOCALMODELREPO/${ADDR[-1]}/config.pbtxt
-
+	
 	PLATFORM=$(grep -m 1 "^platform:" "$CONFIG")
-
+	
 	cat <<EOF >> $CONFIG
 
 instance_group [
@@ -367,6 +385,7 @@ list_models(){
 		fi
 		mkdir $TMPDIR/$LOCALMODELREPO
 	fi
+
 	for MODEL in ${MODELS[@]}; do
 		# check if file was provided rather than directory
 		if [ -f "$MODEL" ]; then
@@ -458,18 +477,21 @@ scram_tag(){
 }
 
 driver_docker(){
-	docker run --rm --entrypoint env ${IMAGE} | grep "CUDA_DRIVER_VERSION="
+	$DOCKER run --rm --entrypoint env ${IMAGE} | grep "CUDA_DRIVER_VERSION="
 }
 
-driver_singularity(){
-	source ${SANDBOX}/.singularity.d/env/10-docker2singularity.sh && echo $CUDA_DRIVER_VERSION
+driver_apptainer(){
+	D2S=${SANDBOX}/.singularity.d/env/10-docker2singularity.sh
+	if [ -f "$D2S" ]; then
+		source $D2S && echo $CUDA_DRIVER_VERSION
+	fi
 }
 
 compat_docker(){
-	docker cp $(docker create --rm ${IMAGE}):${COMPAT_SCRIPT} .
+	$DOCKER cp $($DOCKER create --rm ${IMAGE}):${COMPAT_SCRIPT} .
 }
 
-compat_singularity(){
+compat_apptainer(){
 	cp ${SANDBOX}/${COMPAT_SCRIPT} .
 }
 
@@ -514,8 +536,12 @@ check_drivers(){
 		if [ "$PWD" == "$TMPDIR" ]; then
 			$DRYRUN $COMPAT_FN
 			COMPAT_SCRIPT_BASE=$(basename $COMPAT_SCRIPT)
-			$DRYRUN sed -i 's/LD_LIBRARY_PATH="${_CUDA_COMPAT_REALLIB}"/&; LD_PRELOAD=""/' $COMPAT_SCRIPT_BASE
-			COMPAT_SCRIPT_MOUNT="$COMPAT_SCRIPT_BASE:$COMPAT_SCRIPT"
+			# newer containers already include this fix, no need to do it twice
+			if ! grep -Fq 'LD_PRELOAD=""' $COMPAT_SCRIPT_BASE; then
+				$DRYRUN sed -i 's/LD_LIBRARY_PATH="${_CUDA_COMPAT_REALLIB}"/&; LD_PRELOAD=""/' $COMPAT_SCRIPT_BASE
+				COMPAT_SCRIPT_PATH=$(readlink -f $TMPDIR/$COMPAT_SCRIPT_BASE)
+				COMPAT_SCRIPT_MOUNT="$COMPAT_SCRIPT_PATH:$COMPAT_SCRIPT"
+			fi
 		fi
 		return 0
 	else
@@ -537,12 +563,12 @@ else
 	if [ -n "$GPU" ]; then
 		EXTRA="--nv"
 	fi
-	START_FN=start_singularity
-	TEST_FN=test_singularity
-	STOP_FN=stop_singularity
-	DRIVER_FN=driver_singularity
-	COMPAT_FN=compat_singularity
-	PROG_NAME=Singularity
+	START_FN=start_apptainer
+	TEST_FN=test_apptainer
+	STOP_FN=stop_apptainer
+	DRIVER_FN=driver_apptainer
+	COMPAT_FN=compat_apptainer
+	PROG_NAME=Apptainer
 fi
 
 if [ "$OP" == check ]; then
@@ -562,7 +588,7 @@ elif [ "$OP" == start ]; then
 	if [ "$PORT_EXIT" -ne 0 ]; then exit $PORT_EXIT; fi
 
 	make_tmp
-	
+
 	list_models
 
 	# after make_tmp because this may create file in tmp dir
