update of hltIntegrationTests and hltListPaths scripts
The "hltListPaths" script is updated to support FinalPaths, give the option to ignore paths by name (by means of regular expressions), and give the option to ignore paths that depend on the result of other paths in the same job.

The "hltIntegrationTests" script is updated to ignore Paths that depend on the result of other Paths in the same job, as by construction those cannot be tested without other Paths.

diff --git a/HLTrigger/Configuration/scripts/hltCompareResults b/HLTrigger/Configuration/scripts/hltCompareResults
--- a/HLTrigger/Configuration/scripts/hltCompareResults
+++ b/HLTrigger/Configuration/scripts/hltCompareResults
@@ -8,12 +8,9 @@ function err() {
   echo -e "$@" 1>&2
 }
 
-
-# exract list of triggers
-TRIGGERS=$(cat hlt.py | grep 'cms.Path' | sed -e's/process.\(\w\+\) = cms.Path.*/\1/' | grep -v HLTriggerFinalPath | grep -v HLT_LogMonitor)
-
-# check if thw menu as a whole was run
 touch issues.txt
+
+# check if the menu as a whole was run
 if ! [ -f "hlt.done" ]; then
   err "ERROR: Execution of the full HLT menu failed.\nPlease check the contents of 'hlt.log' for details."
   cat >> issues.txt <<EOF
@@ -22,7 +19,18 @@ EOF
   exit 1
 fi
 
-# compare the results of running each path by iteslf with those from the full menu
+# extract list of triggers
+if ! [ -f "paths.txt" ]; then
+  err "ERROR: File \"paths.txt\" does not exist (must contain the list of paths used in the integration tests)."
+  cat >> issues.txt <<EOF
+paths.txt
+EOF
+  exit 1
+fi
+
+TRIGGERS=$(cat paths.txt)
+
+# compare the results of running each path by itself with those from the full menu
 STATUS=0
 for TRIGGER in $TRIGGERS; do
   if ! [ -f ${TRIGGER}.done ]; then
