add  --skip and --events options

diff --git a/HLTrigger/Configuration/scripts/hltIntegrationTests b/HLTrigger/Configuration/scripts/hltIntegrationTests
--- a/HLTrigger/Configuration/scripts/hltIntegrationTests
+++ b/HLTrigger/Configuration/scripts/hltIntegrationTests
@@ -15,17 +15,20 @@ HELP="Run the integration tests over all paths in a given HLT menu.
 
 Usage:
   $NAME -h|--help
-  $NAME [-d|--dir WORKDIR] [-s|--setup SETUP] [-i|--input RAW] MENU
+  $NAME [-d|--dir WORKDIR] [-s|--setup SETUP] [-i|--input RAW] [-j|--jobs JOBS] [-x|--extra OPTIONS] [--mc] 
+        [ [-n|--size EVENTS] [-k|--skip EVENTS] | [-e|--events EVENTS] ] MENU
 
   MENU is the HLT menu to test. 
   
   -s | --setup SETUP        Use the Services and EventSetup modules from a different menu 
                             (usefull when testing a ConfDB area with only some new paths)
-  -d | --dir   WORKDIR      Create all files and run all tests inside WORKDIR (defauls: ./hltintegration)
-  -i | --input INPUT        Use the specified RAW data file as input
-  -n | --size  EVENTS       Run on EVENTS events (-1 for all, default is 100)
-  -j | --jobs  JOBS         Run JOBS jobs in parallel (default is 4)
-  -x | --extra OPTIONS      Pass OPTIONS directly to hltGetConfiguration
+  -d | --dir    WORKDIR     Create all files and run all tests inside WORKDIR (defauls: ./hltintegration)
+  -i | --input  INPUT       Use the specified RAW data file as input
+  -n | --size   EVENTS      Run on EVENTS events (-1 for all, default is 100)
+  -k | --skip   EVENTS      Skip the first EVENTS (default is 0)
+  -e | --events EVENTS      Run on a comma-separated list of EVENTS, a VEventRange
+  -j | --jobs   JOBS        Run JOBS jobs in parallel (default is 4)
+  -x | --extra  OPTIONS     Pass OPTIONS directly to hltGetConfiguration
        --mc                 Run over MC instead of data (the default)
   -h | --help               Print this help message and exit.
 
@@ -40,6 +43,9 @@ Usage:
 
   It's possible to pass arbitrary command line options to hltGetConfiguration, using \"-x --option\".
   To pass multiple options, enclose them in quotes, or use \"-x\" more than once. 
+
+  Note: '--events' is not supported together with '--size' or '--skip'.
+
 
 Exmples:
 
@@ -61,7 +67,7 @@ Exmples:
 "
 
 # parse command line argument and options
-OPTS=$(getopt -n "$NAME" -o "s:d:i:j:n:x:h" -l "setup:,dir:,input:,jobs:,size:,mc,extra:,help" -- "$@")
+OPTS=$(getopt -n "$NAME" -o "s:d:i:j:n:k:e:x:h" -l "setup:,dir:,input:,jobs:,size:,skip:,events:,mc,extra:,help" -- "$@")
 
 # invalid options
 if [ $? != 0 ]; then 
@@ -75,10 +81,14 @@ MENU=""
 SETUP=""
 INPUT=""
 SIZE=100
+SKIP=0
+EVENTS=""
 JOBS=4
 WORKDIR="hltintegration"
 EXTRA=""
 DATA="--data"
+
+SELECTION=""
 
 # parse options
 while true; do
@@ -100,12 +110,40 @@ while true; do
       shift 2
       ;;
     "-n" | "--size" )
+      if [ "$SELECTION" == "complex" ]; then
+        err "'--events' is not supported together with '--size' or '--skip'"
+        exit 1
+      fi
+      SELECTION="simple"
       SIZE=$2
       if ((SIZE == 0)) && [ "$SIZE" != "0" ]; then
         err "$NAME error: invalid option \"$1 $2\""
         err "Try '$NAME --help' for more information."
         exit 1
       fi
+      shift 2
+      ;;
+    "-k" | "--skip" )
+      if [ "$SELECTION" == "complex" ]; then
+        err "'--events' is not supported together with '--size' or '--skip'"
+        exit 1
+      fi
+      SELECTION="simple"
+      SKIP=$2
+      if ((SKIP == 0)) && [ "$SKIP" != "0" ]; then
+        err "$NAME error: invalid option \"$1 $2\""
+        err "Try '$NAME --help' for more information."
+        exit 1
+      fi
+      shift 2
+      ;;
+    "-e" | "--events" )
+      if [ "$SELECTION" == "simple" ]; then
+        err "'--events' is not supported together with '--size' or '--skip'"
+        exit 1
+      fi
+      SELECTION="complex"
+      EVENTS="$2"
       shift 2
       ;;
     "-j" | "--jobs" )
@@ -156,14 +194,33 @@ cd     "$WORKDIR"
 TRIGGERS=$(hltListPaths -p "$MENU")
 
 # print some info
-log "Will run $(echo $TRIGGERS | wc -w) HLT paths over $SIZE events, with $JOBS jobs in parallel"
+if [ "$SELECTION" == "complex" ]; then
+  log "Will run $(echo $TRIGGERS | wc -w) HLT paths over $(echo $EVENTS | tr ',' '\n' | wc -l) events, with $JOBS jobs in parallel"
+else
+  log "Will run $(echo $TRIGGERS | wc -w) HLT paths over $SIZE events, with $JOBS jobs in parallel"
+fi
 
 # create all dumps
 log "Extracting full menu dump"
 hltGetConfiguration "$MENU" --full --offline $DATA $INPUT --unprescale --process "TEST$(date -u +'%Y%m%d%H%M%S')" $EXTRA > hlt.py
 
-# adapt the number of events
-sed -i -e "s/input = cms.untracked.int32( .* )/input = cms.untracked.int32( $SIZE )/" hlt.py
+# select which events to run on
+if [ "$SELECTION" == "complex" ]; then
+  cat >> hlt.py << @EOF
+# event selection customised by hltIntegrationTests
+if 'maxEvents' in process.__dict__:
+    delattr(process, 'maxEvents')
+process.source.eventsToProcess = cms.untracked.VEventRange( '$(echo $EVENTS | sed -e"s/,/','/g")' )
+@EOF
+else
+  cat >> hlt.py << @EOF
+# event selection customised by hltIntegrationTests
+if 'maxEvents' in process.__dict__:
+    delattr(process, 'maxEvents')
+process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32( $SIZE) )
+process.source.skipEvents = cms.untracked.uint32( $SKIP )
+@EOF
+fi
 
 # dump the menu name, and its release template
 log "HLT menu: $(head -n1 hlt.py | cut -c 3-)"
